#!/usr/bin/env python3
"""UserPromptSubmit hook: Detect milestone commands and update status.

Listens for special commands in user prompts:
- /milestone <description> - Record a milestone
- /status - Force status update
- /handoff - Generate handoff document

This enables manual triggering of status updates for major work completions.
"""

import json
import sys
import re
from datetime import datetime
from pathlib import Path


def get_claude_dir() -> Path:
    """Get .claude directory in current working directory."""
    return Path.cwd() / ".claude"


def load_state(claude_dir: Path) -> dict:
    """Load session state from file."""
    state_file = claude_dir / ".session-state.json"
    if state_file.exists():
        try:
            return json.loads(state_file.read_text())
        except (json.JSONDecodeError, IOError):
            pass
    return {
        "action_count": 0,
        "completed_tasks": [],
        "session_start": datetime.now().strftime("%H:%M:%S"),
        "milestones": []
    }


def save_state(claude_dir: Path, state: dict):
    """Save session state to file."""
    state_file = claude_dir / ".session-state.json"
    state_file.write_text(json.dumps(state, indent=2))


def record_milestone(claude_dir: Path, description: str):
    """Record a milestone in session state and STATUS.md."""
    state = load_state(claude_dir)

    milestone = {
        "time": datetime.now().strftime("%H:%M:%S"),
        "description": description,
        "date": datetime.now().strftime("%Y-%m-%d")
    }
    state.setdefault("milestones", []).append(milestone)
    save_state(claude_dir, state)

    # Also append to STATUS.md
    status_file = claude_dir / "STATUS.md"
    if status_file.exists():
        content = status_file.read_text()
    else:
        content = f"# Project Status\n\n*Auto-generated by Claude Code hooks*\n\n## Milestones\n\n"

    # Add milestone entry
    if "## Milestones" not in content:
        content += "\n## Milestones\n\n"

    # Insert after Milestones header
    lines = content.split('\n')
    for i, line in enumerate(lines):
        if line.strip() == "## Milestones":
            lines.insert(i + 1, f"\n- **[{milestone['date']} {milestone['time']}]** {description}")
            break

    status_file.write_text('\n'.join(lines))

    return milestone


def generate_handoff(claude_dir: Path) -> str:
    """Generate a handoff document for session continuity."""
    state = load_state(claude_dir)
    now = datetime.now()

    # Count activity
    activity_file = claude_dir / "activity.jsonl"
    counts = {"edits": 0, "writes": 0, "commands": 0}
    files = set()

    if activity_file.exists():
        today = now.strftime("%Y-%m-%d")
        with open(activity_file) as f:
            for line in f:
                try:
                    entry = json.loads(line)
                    if entry.get("timestamp", "").startswith(today):
                        tool = entry.get("tool", "")
                        if tool in ("Edit", "MultiEdit"):
                            counts["edits"] += 1
                        elif tool == "Write":
                            counts["writes"] += 1
                        elif tool == "Bash":
                            counts["commands"] += 1
                        if "file" in entry:
                            try:
                                files.add(str(Path(entry["file"]).relative_to(Path.cwd())))
                            except ValueError:
                                files.add(entry["file"])
                except json.JSONDecodeError:
                    continue

    # Format completed tasks
    tasks_section = ""
    if state.get("completed_tasks"):
        tasks_section = "## Completed This Session\n\n"
        for task in state["completed_tasks"]:
            task_id = task.get("id", "?")
            task_subject = task.get("subject", f"Task #{task_id}")
            tasks_section += f"- [{task['time']}] {task_subject}\n"
        tasks_section += "\n"

    # Format milestones
    milestones_section = ""
    if state.get("milestones"):
        milestones_section = "## Milestones\n\n"
        for m in state["milestones"]:
            milestones_section += f"- [{m['time']}] {m['description']}\n"
        milestones_section += "\n"

    # Format files
    files_section = "## Files Modified\n\n"
    for f in sorted(files)[:20]:
        files_section += f"- {f}\n"
    if len(files) > 20:
        files_section += f"- ... and {len(files) - 20} more\n"
    files_section += "\n"

    handoff = f"""# Session Handoff

*Generated: {now.strftime("%Y-%m-%d %H:%M:%S")}*
*Session started: {state.get('session_start', 'unknown')}*

## Summary

This session made **{counts['edits']} edits**, **{counts['writes']} writes**, and ran **{counts['commands']} commands**.

{tasks_section}{milestones_section}{files_section}## Next Steps

<!-- Add what should be done next -->

## Notes

<!-- Add any important context for the next session -->
"""

    handoff_file = claude_dir / "HANDOFF.md"
    handoff_file.write_text(handoff)

    return str(handoff_file)


def main():
    try:
        # Read input from stdin
        input_data = json.load(sys.stdin)

        prompt = input_data.get("prompt", "")

        # Check for milestone command
        milestone_match = re.search(r'/milestone\s+(.+?)(?:\n|$)', prompt, re.IGNORECASE)
        if milestone_match:
            description = milestone_match.group(1).strip()
            claude_dir = get_claude_dir()
            claude_dir.mkdir(exist_ok=True)
            milestone = record_milestone(claude_dir, description)
            print(json.dumps({
                "systemMessage": f"🏁 Milestone recorded: \"{description}\" → .claude/STATUS.md"
            }))
            sys.exit(0)

        # Check for handoff command
        if '/handoff' in prompt.lower():
            claude_dir = get_claude_dir()
            if claude_dir.exists():
                handoff_path = generate_handoff(claude_dir)
                print(json.dumps({
                    "systemMessage": f"📋 Handoff document generated → {handoff_path}"
                }))
                sys.exit(0)

        # Check for status command (force update)
        if '/status' in prompt.lower():
            claude_dir = get_claude_dir()
            if claude_dir.exists():
                state = load_state(claude_dir)
                actions = state.get('action_count', 0)
                tasks = len(state.get('completed_tasks', []))
                milestones = len(state.get('milestones', []))
                print(json.dumps({
                    "systemMessage": f"📊 Session: {actions} actions | {tasks} tasks completed | {milestones} milestones"
                }))
                sys.exit(0)

        # No special commands, pass through
        print(json.dumps({}))

    except Exception as e:
        print(json.dumps({"systemMessage": f"Milestone hook: {e}"}))

    sys.exit(0)


if __name__ == "__main__":
    main()
